### ISSUE TITLE
BTC sent to fund ether expired

### ISSUE THREAD

**Issue by gkchege** [OutCast3k/coinbin#100]
Hi. I was sending some btc to the address provided - 15HrvVcPnVa4H2jPHZWDKZ9bRm6GmvQEET - and I have the txn ID. By the time I completed loading to the Ethereum Wallet V0.8.10, the windows said address was expired. No Eth has been credited to my wallet. Kindly assist.

**Comment by OutCast3k** [comment]
Could you please clarify what you mean? You state btc but also eth.

Thanks
