### ISSUE TITLE
Unspent to fee

### ISSUE THREAD

**Issue by 0x49D1** [OutCast3k/coinbin#101]
Can someone explain me why must I send all the unspent money as a fee? For example if I don't need to spend whole amount I have on my "cold" wallet I need to create 2 transfers now (in 1 transaction): one to the destination and one to self + some amount as a fee. Using this "hack" I can return the amount I want to store back to the wallet. But why not just allow me to point the fee I want (for example I can take recommended from https://bitcoinfees.21.com )?

**Comment by OutCast3k** [comment]
All unspent money is returned to you as change please see https://en.bitcoin.it/wiki/Change for more info.
