### ISSUE TITLE
private key and lost account

### ISSUE THREAD

**Issue by trader777** [OutCast3k/coinbin#102]
hey, i forgot my login name but i know my bitcoin addres and have private key.. How can i get acces to my wallet???

**Comment by maxwhaleDE** [comment]
You can import it, using f.e. Electrum.

**Comment by OutCast3k** [comment]
You can import your private key (starting with L,K or 5) to nearly any bitcoin client.

You can also use the #newTransaction Page to manually spend your funds, and then sign it and broadcast your transaction.

All the best.
