### ISSUE TITLE
fee will take all remaining unspent . please guide to avoide

### ISSUE THREAD

**Issue by sajeesolutions** [OutCast3k/coinbin#104]
Can someone explain me why must I send all the unspent money as a fee? For example if I don't need to spend whole amount I have on my "cold" wallet I need to create 2 transfers now (in 1 transaction): one to the destination and one to self + some amount as a fee. Using this "hack" I can return the amount I want to store back to the wallet.

**Comment by dabura667** [comment]
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... that's not a "hack"... that's how bitcoin is supposed to work. https://en.bitcoin.it/wiki/Change
