### ISSUE TITLE
Coinb.in and blockr show no inputs

### ISSUE THREAD

**Issue by Friedeman** [OutCast3k/coinbin#105]
Hello,
I traded with a partner and used coinb.in multi-sig.

The redeem script 
**_522102ac174028778912dac983b886cf87a242e44e07d5cbdbab214f03e9a83616f840210276ae95c64f264f78391fe0799882bea6edfd66650c44803a5c5462f50a3919a921020e02f631816560e646d23486ad3a210b452f5b41b6d8fd0814db4a67147f605d53ae_**

has been generated and shows the following wallet:

**_3P2jxfzHTjxvq29P85nGddNKqUkcXfeiYi_**

The trade has been successfull and we wanted now to create a transaction using the redeem script above.
Unfortunately, after loading the redeem script, there are no inputs and no outpots shown (both on 0.00000).

The linked wallet (https://btc.blockr.io/address/info/3P2jxfzHTjxvq29P85nGddNKqUkcXfeiYi) shows 0.000 BTC as well.

**BUT** if I check any other sites like blockchain, chain.so etc., the wallet shows confirmed inputs:
https://blockchain.info/address/3P2jxfzHTjxvq29P85nGddNKqUkcXfeiYi

I was  transferring like 0.0002166 BTC to check if it helps, too but even they didn't show up.

How can I get my money now? 

Thanks for help. Leave your wallet for donations in case of successfull!

**Comment by dabura667** [comment]
coinb.in by default uses blockr

It looks like a bug with blockr.

Try reporting the bug to them.

**Comment by Friedeman** [comment]
I did - but the last blockr.io post on facebook had been 2015 and twitter 3 months ago. 
To my bug report, they haven't responded yet.

If they won't react, my money gone? What else could I do?

**Comment by dabura667** [comment]
iirc you can change the site you use in coinb.in's settings

**Comment by Friedeman** [comment]
Nope, unfortunately not: With Bitcoin there is only blockr.io as far as I can see :(

**Comment by maxwhaleDE** [comment]
Dude, I have exactly the same problem. Can anybody help? Also me, I'm willing to donate for help

**Comment by OutCast3k** [comment]
Hi there,

The bitcoin demon running had failed and this had gone unnoticed, when it fails our system will attempt to retrieve unspent outputs and balances from blockr.io, but clearly they are having issues to.

As of now, we have a second node running on a separate server which should give more stability. Further more should both of our nodes fail we will use blockr.io and blockchain.info to compare and return more accurate balances.

If anyone has any other problems, please feel free to get in touch.
