### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by davetherave123** [OutCast3k/coinbin#108]
Hoping someone can help.

I set up a new address using the new tab at the top of the coinb.in website and then transferred some funds into this. However, I now unable to retrieve the funds and nothing has been put into the wallet on my account (which I think has a different address).

Sorry, new to this but really confused to how to get the money and can see that the transaction went through.

Thanks

**Comment by zilveer** [comment]
May I ask what address it is so we can help you ?

**Comment by davetherave123** [comment]
114Z3JUj39E6dn4oqvDEMQroMDJpTGPaMw

thanks

**Comment by zilveer** [comment]
I think this is really strange:

on coinb.in there is an input of 0.01583555 BTC 

which you can see here:
[https://blockchain.info/address/114Z3JUj39E6dn4oqvDEMQroMDJpTGPaMw](https://blockchain.info/address/114Z3JUj39E6dn4oqvDEMQroMDJpTGPaMw)

and on this website there is nothing 0 inputs:

[https://btc.blockr.io/address/info/114Z3JUj39E6dn4oqvDEMQroMDJpTGPaMw](https://btc.blockr.io/address/info/114Z3JUj39E6dn4oqvDEMQroMDJpTGPaMw)

I find it strange why it states 0.01583555 BTC on blockchain.info and 0 BTC on blockr.io

Anyone else who knows why we get 2 different inputs??

regards

**Comment by dudewheresmycoinslol** [comment]
Check this address 194ZzWvFiRkigvDqYebfwg4GaJKj56YB7e does not show any transactions via BTC.blockr but has a .309 BTC value on block chain. 14XHBrjMLzH8uamMcB121fqkfsCuLDgLgb this is the sender of that .309 BTC to previous address...also void of transactions on blockr. Both of those addresses we're generated via coinb.in

**Comment by dudewheresmycoinslol** [comment]
I've used coinb.in exclusively throughout my 2.5 yrs of bitcoining using 20-30 differ addresses...never a prob till recent, login info doesn't work for address with the .309 BTC input

**Comment by OutCast3k** [comment]
Hey there,

The API request made to the "balance" call is returning 0.309 BTC. As seen here: http://coinb.in/api/?uid=1&key=12345678901234567890123456789012&setmodule=addresses&request=bal&address=194ZzWvFiRkigvDqYebfwg4GaJKj56YB7e

The unspent outputs also seem to be properly showing via the API as seen here:

http://coinb.in/api/?uid=1&key=12345678901234567890123456789012&setmodule=addresses&request=unspent&address=194ZzWvFiRkigvDqYebfwg4GaJKj56YB7e

Keep in mind the values are in satoshis

If you could provide some more information to reproduce your steps and include errors or screenshots that'd be great.

Thanks
