### ISSUE TITLE
Wallet shows no funds even though blockchain shows comformations

### ISSUE THREAD

**Issue by Gruntydog** [OutCast3k/coinbin#110]
as I said up top the transaction has 19 Comformations and still shows an empty wallet and won't let me send btc.

**Comment by globaltoken** [comment]
Do you use BCC ?

**Comment by Gruntydog** [comment]
No, btc, for that matter I've used the wallet 5 times and it doesen't even show the left over funds from those transactions, just 0.00btc.

**Comment by globaltoken** [comment]
Is your Node fully synced?

**Comment by Gruntydog** [comment]
I have no idea on how to check that on this wallet.

**Comment by dudewheresmycoinslol** [comment]
Wondering if recent DNM siezures by LE have anything to do with it?? Ultimately there's no telling where exactly the coins we receive come from... possibly received "tainted" coins and LE froze them???

**Comment by OutCast3k** [comment]
Are you happy to share the wallet address with us?

I can then at least check what the API is returning and compare it against another block explorer.

Thanks
