### ISSUE TITLE
Bitcoin Cash Support?

### ISSUE THREAD

**Issue by imcoddy** [OutCast3k/coinbin#112]
Will coinb.in add Bitcoin Cash support?

**Comment by dabura667** [comment]
I came up with a checklist of stuff to be done if you wanna do it.

https://github.com/OutCast3k/coinbin/pull/111#issuecomment-320448351

**Comment by NxtChg** [comment]
Your checklist is very hard to read. Can't you write something clear? If you know how to do it, it shouldn't be hard for you to explain what needs to be done clearly.

**Comment by NxtChg** [comment]
@dabura667 or maybe you would be interested in a bounty? https://www.xbtfreelancer.com/prj/4389/add-bitcoin-cash-support

**Comment by dabura667** [comment]
@NxtChg What is not clear about my instructions?

Also, $75 budget is way too small. The only bids you'll get on that are people who probably don't know what they're doing.

**Comment by NxtChg** [comment]
> Also, $75 budget is way too small. 

It's $50, not $75.

**Comment by OutCast3k** [comment]
It'll likely get added eventually yes. Still reviewing the pull request.

Thanks for the support!
