### ISSUE TITLE
redeemScripts >520 bytes must be rejected

### ISSUE THREAD

**Issue by dabura667** [OutCast3k/coinbin#118]
A user on reddit reported generating a multisig that had a redeemScript >520 bytes and coinbin generated the P2SH address without warning.

As per consensus rules this redeemscript is a blackhole that can never be sent from.

https://www.reddit.com/r/Bitcoin/comments/74375h/i_have_a_p2sh_multisig_redeem_script_that_is_over/

**Comment by OutCast3k** [comment]
thanks for reporting this, just issued a fix for it.
