### ISSUE TITLE
Outputs in created transactions gets removed

### ISSUE THREAD

**Issue by Mysticsam** [OutCast3k/coinbin#12]
Hi i just tried to make a transaction with coinb.in .

![skarmbild fran 2015-01-17 01 37 34](https://cloud.githubusercontent.com/assets/2348702/5786681/9e9d881e-9de9-11e4-89b5-b235222bed07.png)

![skarmbild fran 2015-01-17 01 37 47](https://cloud.githubusercontent.com/assets/2348702/5786686/aa2c2898-9de9-11e4-9bb1-bcce700b7cfb.png)

![skarmbild fran 2015-01-17 01 38 07](https://cloud.githubusercontent.com/assets/2348702/5786691/b317e3e8-9de9-11e4-80df-5cd74354fd4f.png)

As you can see the outputs of the transaction get removed.

**Comment by dabura667** [comment]
That's because your address is invalid. So you are not generating any outputs.

**Comment by dabura667** [comment]
One way you can tell this is that if you had created a valid output with 4.99999950 BTC to it, you would see the pattern `ce64cd1d00000000` before the output.

Since you don't see this pattern, nowhere in the tx does it refer to "4.99999950 BTC"

**Comment by dabura667** [comment]
Also your input seems to be weird... you might be inserting the incorrect information for the "Address, WIF key or Multisig Redeem Script" part as well.

**Comment by Mysticsam** [comment]
Hi i am using testnet addresses in that the problem? 

I am not using the "Address, WIF key or Multisig Redeem Script" part as i dont know how to use it. 
It have worked fine before. 

The output address is not invalid , from my bitcoin core testnet: 
￼
validateaddress n1yrPA1kpyrndJ98yR7PtbvdFsjer84UoP
{
"isvalid" : true,
"address" : "n1yrPA1kpyrndJ98yR7PtbvdFsjer84UoP",
"ismine" : true,
"isscript" : false,
"iscompressed" : true,
"account" : ""
}

Is it because the address is compressed? 

I will try to make a new transaction: 

from txid: 38b262280c88b6ef02a6414b2bccc488687ea3d10a538cc47b600297b23fe14d

![skarmbild fran 2015-01-18 17 45 31](https://cloud.githubusercontent.com/assets/2348702/5793174/60782286-9f3a-11e4-897c-37db97d48f77.png)


![skarmbild fran 2015-01-18 17 48 25](https://cloud.githubusercontent.com/assets/2348702/5793175/6df654aa-9f3a-11e4-9e6b-d5f4b205dc61.png)


Txid: 38b262280c88b6ef02a6414b2bccc488687ea3d10a538cc47b600297b23fe14d 
N:0
Script: eaf5647755757e9710eb0cbd4f0e2e28bd76ca5a


![skarmbild fran 2015-01-18 17 48 54](https://cloud.githubusercontent.com/assets/2348702/5793177/739dd964-9f3a-11e4-9760-9e851a1e1c9e.png)


![skarmbild fran 2015-01-18 17 49 21](https://cloud.githubusercontent.com/assets/2348702/5793178/78abee1e-9f3a-11e4-84cb-04d7e705d1d7.png)

As you can see, the same result.

**Comment by dabura667** [comment]
Nope, it's not because it is compressed. It is because it is testnet.

Unfortunately, coinbin is not testnet enabled.

**Comment by Mysticsam** [comment]
Ok Its good to know what the problem is. But i have been able too do this before without problem back when i told you about the lack of testnet support. I want to use your solution because it is easier than bitcoin core client and but i don't want to have to use real bitcoin to test different types of transactions.

**Comment by OutCast3k** [comment]
Testnet isnt supported, yet. Please read this post https://github.com/OutCast3k/coinbin/issues/2#issuecomment-96614487
