### ISSUE TITLE
Redeem script needed for segwit addresses

### ISSUE THREAD

**Issue by genus1** [OutCast3k/coinbin#122]
When creating a new transaction if using a Segwit address for Address, WIF key or Redeem Script:, an error returns  You should use the redeem script, not the multisig address!

The challenge is, especially if you have not previously spent from the coin, it is hard to derive the Redeem Script.  Also if the coin is in like Trezor, the redeem script is not available even from the wallet.

Maybe the message should say, "You should use the redeem script, not the multisig or segwit address!"  This would alert the user that something special is needed with segwit addresses.

It should be noted, that even when using the coinbin wallet, the private key is available for signing but not the redeem script.  Maybe, the redeem script should be added to the wallet page for a multisig address along with the public and private keys?  I know I can create a new segwit address and the redeem script is available.  This should show in the wallet.

**Comment by OutCast3k** [comment]
Some good points, I'll try to get them addressed in the next updates

**Comment by OutCast3k** [comment]
This has now been added to the wallet section of coinb.in in the most recent commit

Thanks
