### ISSUE TITLE
Obfuscated JavaScript prevents review

### ISSUE THREAD

**Issue by rapodaca** [OutCast3k/coinbin#13]
I've been reviewing Coinb.in, and like the approach and functionality.

In browsing the source code, I noticed several obfuscated JavaScript source files. For example, AES.js (there are others):

https://github.com/OutCast3k/coinbin/blob/master/js/aes.js

Obfuscation makes reviewing the code difficult. Are there any plans to replace these files with unobfuscated versions?

**Comment by jpswade** [comment]
This isn't obfuscated, it's minification.

You'll find that this code is identical to the distribution here:

http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js
https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js

I advise that you review this project:
https://code.google.com/p/crypto-js/

Enjoy.

**Comment by OutCast3k** [comment]
As jpswade said, the lib is not obfuscated, its minified and the source can be found in the links provided.

Thanks.
