### ISSUE TITLE
insane transaction fee

### ISSUE THREAD

**Issue by wire67** [OutCast3k/coinbin#131]
Hi,
I made a 0.002 BTC test transfer to my second wallet, I had 0.004 BTC and it's all gone, it took 0.002 BTC of fees! 
This was not urgent or anything important, so why did it take 50% / $30 of fees !?
How can I change the fee?

I tried to change the fee by removing the readonly attribute but apparently it hasn't been taken in account.

Latest release Version 1.3

**Comment by OutCast3k** [comment]
Hi,

Coinb.in's tool set is really designed for advanced users who understand the bitcoin protocol, and its clear from the question you don't which is unfortunate. 

It sounds like you are using the #newTransaction page to build a transaction by hand as you have described removing the readonly attribute.

It appears you've also ignored the dialog box which would have popped up stating you are paying a high fee. 

> **Warning High Fee!**
> Please be aware that you have created a transaction with what seems to be a very high fee of 0.00200000 BTC!
> 

Finally, the way bitcoin works is, what isn't spent is used as a fee. This means you are required to manually provide a change address. 

https://en.bitcoin.it/wiki/Change

Sorry for you bad luck.

**Comment by wire67** [comment]
Hi,

Thanks for your help.

> Coinb.in's tool set is really designed for advanced users who understand the bitcoin protocol, and its clear from the question you don't which is unfortunate.

Correct. I was googling for a wallet that works offline, this is how I found coinbin and it didn't appear to me that it is designed for advanced users only.

> It appears you've also ignored the dialog box which would have popped up stating you are paying a high fee.

Unfortunately the dialog didn't appear because I manually edited the fee.
And later I could not see the fee from the verify and sign pages.

Which standalone HTML tool should be used for beginners that simply want to transfer their coins from a cold wallet?

Thank you.

**Comment by OutCast3k** [comment]
Hi,

Glad you found us, its not for advanced users _only_, but you certainly need to understand some of the basics to avoid loosing money. I'm glad you didn't loose too much and I hope this experience doesn't put you off, it shouldn't. But unfortunately this is not a design flaw, coinb.in has chosen to be this way as it is how the transactions fundamentally work, change addresses need to be added, in this case manually.

Its strange the dialog didn't appear, going from memory it should show if the fee is greater than 0.001, but perhaps editing the field had something to do with not showing.

I'm not aware of any standalone HTML tool-set that exists for beginners like coinb.in but you can import your keys into almost any half decent mobile or desktop wallet.

All the best.
