### ISSUE TITLE
"Missing inputs" while signed & verified ok

### ISSUE THREAD

**Issue by RussianSwiss** [OutCast3k/coinbin#139]
What's wrong with this tx?

0100000002499aff6fb199ba30b70b60f1a1da05f9c24a982f92ed6c80d3f1d2a454973f87000000006b483045022100e6cc3c75644b4f946a19723952a7b8435f8fdce5aef63c5d2bf8292426f4b0d502202efaa27e64ed20f47e3793e2267a7d713bdec06b442019b1cee64e38c32bc332012103171066f8a31e32319fbfbfe2c471ac7de3986fc96ac9da336cc5dd17325d1307ffffffff56828fc2bc8381e214d86afee11a30c49e72a4ecc2261d36544944dc54eaa741010000006b483045022100cef88be6912df5f310bfac8cf56cf1c6971892eee68cf44cbef2c45c09e83d1802200f597d80357bde9c3b5106e98a24084de99fce0bdc00de1890cbe0518d8deeee012103ce47ca0532237078ac6467503159538b0d6f75c6caa4a5576e021ae7fbfd1ff3ffffffff0280d01d05000000001976a914a1ccee5bb51e8408644e227e9d4ec535dc49736b88ac405489000000000017a914da829bf5bf2f7c1a025ecd1e197e6f6cf06135688700000000

**Comment by dion111** [comment]
Im not dev but I now..

**Comment by OutCast3k** [comment]
It means your inputs are already spent and cant be used.
