### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by bulldozer2003** [OutCast3k/coinbin#14]
http://coinb.in is down.

**Comment by bulldozer2003** [comment]
A good option would be to use github.to using coinbin/coinbin.github.io

**Comment by OutCast3k** [comment]
Hey, it seems that the domain has expired and I either wasn't reminded or missed the reminder. Either way, I've just processed the renewal, and placed it on auto renew. It should become active very shortly. Thanks for brining this to my attention.
