### ISSUE TITLE
Antivirus marks the website as malicious/phishing

### ISSUE THREAD

**Issue by informatorius** [OutCast3k/coinbin#154]
https://www.virustotal.com/#/url/1bcecf5dd69bd0e04f76e673a927a4237c94537d83e5a3683bb6738e61ac4ba4/detection

Even locally downloaded the Avast Webguard gives a warning and blocks script execution because of bad rating of other users.

Adguard plugin also blocks the site because of the virustotal findings

**Comment by OutCast3k** [comment]
I'm not sure why coinbin has been reported, everything seems fine, the file hashes are correct, server seems secure, it's not serving anything it shouldn't be.

I've tried contacted some providers as of a few days ago when it first come to my attention, but have had no resolution yet. Any help would be greatly appreciated.
