### ISSUE TITLE
#newTransaction using SegWit P2SH address fails

### ISSUE THREAD

**Issue by Bushstar** [OutCast3k/coinbin#162]
When using the following page...

https://coinb.in/#newTransaction

Using a SegWit address that starts with a 3 the error is...

_You should use the redeem script, not the multisig address!_

Is it possible to update CoinBin to differenciate between a multisig and a backwards compatible SegWit address to be able to unpack and use the SegWit outs puts in that address?

**Comment by dabura667** [comment]
what did you paste exactly?

**Comment by Bushstar** [comment]
We've got this issue with our fork of coinbin using non-multisig SegWit addresses. I tested with random addresses from the Bitcoin explorer presuming most of the addressees starting with 3 are SegWit. Currently out but will generate a new SgeWit address in the Bitcoin client when I get back.

Thanks for a great web wallet by the way.

**Comment by Bushstar** [comment]
For example, a SegWit address created in coinbin.

3B9otY1vDvKvys2xovjSjLSzrYCfEKURzc

**Comment by OutCast3k** [comment]
Hi,

When using a p2sh segwit address (starting with 3) you must still use the redeem script to get your data.

The only way to avoid using a redeem script is to use a fully compatible bech32 address, this starts with bc1 and can still be used throughout coinb.in.

Hope that clears it up for you.

**Comment by Bushstar** [comment]
Understood, thanks.
