### ISSUE TITLE
cannot spend from multisig script

### ISSUE THREAD

**Issue by AndreyViktor** [OutCast3k/coinbin#163]
i have a multisig wallet with some funds that i would like to redeem, but i am getting problem to build the transaction.
created a raw transaction out of the reedem script(arround 85bytes), signed it with one PK(arround 190 bytes), but when i try to sign using the sencond PK the transaction that is generated is exactly the same as the previous as if it hasnt been signed, 190 bytes...

**Comment by OutCast3k** [comment]
More information is needed.

1, Provide the redreem script.
2,The addresses (But not public keys) you have.
3, details of the version of coinb.in you are using and any software you are using such as electrum or Bitcoin core.
4, a signed and unsigned copy of your transaction.
5, browser name and version

**Comment by AndreyViktor** [comment]
reedem script: 5241040ed7927d4d2fc4d3d6fec9f32055e1f216475e37da5e78c542c93ab685010fbb15a23accabf8b5a5427966d0d79258c11b09e5c2c6c1c9e4fa882b16ad412a144104ebca1fa81d43260aa5a1cef9fc276da3dd4bca694ba600f5946e506c43f8ceb66448a0938979a7b7fe29d3d3e291010615af5491b1bd1e81aa37e07f5701e3894104b274ce3e7101cb3380e51909f82245e4d719aba0b23268ae94978122b96c0a8c0c3d86f51b0613829d8fab55b5d32b1914ef3619d9ccc3740d0c932a63848d3f53ae

2.multisig address: 3GesEkgP6EWg5YL1QpD5vBtkdHQwVphhNF

3.i am using the coinb.in 1.4

4.i created an unsigned transaction : 0100000001db86b5ec2bad812380ca83dd1881181b19f89623f6701645a2b5538618ca168e0000000000ffffffff01aa51d900000000001976a9145af26d1c2b75ab6ed7e43d36951aedd830e95fe688ac00000000
then signed it in coinb.in
ant it returned into 0100000001db86b5ec2bad812380ca83dd1881181b19f89623f6701645a2b5538618ca168e000000006a47304402200f5e6a6b82e6303f5c045e1a8a93002fc4b3134574c5861f16f6179d1c53121302205a5a0925aaa348c00d45078a22482d3e0c7da08005ba1ec06cbdc04b935e9e59012103ebca1fa81d43260aa5a1cef9fc276da3dd4bca694ba600f5946e506c43f8ceb6ffffffff01aa51d900000000001976a9145af26d1c2b75ab6ed7e43d36951aedd830e95fe688ac00000000
but when i sign this signed transaction with a second private key it returns this same transaction:
0100000001db86b5ec2bad812380ca83dd1881181b19f89623f6701645a2b5538618ca168e000000006a47304402200f5e6a6b82e6303f5c045e1a8a93002fc4b3134574c5861f16f6179d1c53121302205a5a0925aaa348c00d45078a22482d3e0c7da08005ba1ec06cbdc04b935e9e59012103ebca1fa81d43260aa5a1cef9fc276da3dd4bca694ba600f5946e506c43f8ceb6ffffffff01aa51d900000000001976a9145af26d1c2b75ab6ed7e43d36951aedd830e95fe688ac00000000

5. i am using chrome version 63.0.3239.84

**Comment by AndreyViktor** [comment]
I found about coinb.in/multisig. using this client I could complete sign the transaction with enough signers, I can even verify this transactions and it would say the transaction is signed 2 times out of 2 required but when I try to broadcast it to the network I am getting an 64 error like this: 64: non-mandatory-script-verify-flag (Non-canonical signature: S value is unnecessarily high)

**Comment by OutCast3k** [comment]
I believe this bug might have been caused by the transaction builder, i've since fixed it in the latest release. if you find out otherwise please re-open this ticket.
