### ISSUE TITLE
Cant broadcast transactions with 0 fee.

### ISSUE THREAD

**Issue by btcch2** [OutCast3k/coinbin#167]
Have error 66: min relay fee not met. Please help me with it.

**Comment by dabura667** [comment]
add a fee

**Comment by btcch2** [comment]
Thanks for answer but I need to create a transaction without commission

**Comment by btcch2** [comment]
I need to create a transaction that will wait a long time for the first confirmation. I also tried to create a transaction lock time but received an error 64: non-final

**Comment by dabura667** [comment]
you can't.

the only way to get a 0 fee transaction in a block is if you make the block yourself, or know a miner that makes blocks regularly.

**Comment by dabura667** [comment]
for locktime, nSequence must be non-final.

anything < 0xffffffff should be fine.

**Comment by btcch2** [comment]
Thank you. I just need to create a transaction that will be visible in the blockchain.com and the transaction will wait a long time for the first confirmation. how to do it?

**Comment by dabura667** [comment]
you can't.

wait until BTC gets crowded, then send 1 satoshi/byte tx.

**Comment by dabura667** [comment]
what is your use case? maybe there is a better way.

**Comment by btcch2** [comment]
https://www.youtube.com/watch?v=ycq7O48aPvQ I'm trying to make a double spend. but the first transaction is confirmed too quickly.

**Comment by dabura667** [comment]
What is the double spend for?

**Comment by btcch2** [comment]
I make a video for youtube

**Comment by yottalogical** [comment]
Couldn't you just make two transactions, then broadcast them one after another?

**Comment by yottalogical** [comment]
The broadcast setting you've chose (or left default) requires that you put a certain fee in order for your transaction to be broadcasted. Broadcast your transaction using a different node service (maybe even one not listed on Coinbin) or by using your own node.

**Comment by OutCast3k** [comment]
Unfortunately its unlikely that your transaction will be processed at with a fee of 0.

Further more the coinb.in node doesn't accept transactions with a fee of 0. Minimum is 10 satoshis per transaction.

Its unlikely we will change this.
