### ISSUE TITLE
Transaction verify not working.

### ISSUE THREAD

**Issue by username1565** [OutCast3k/coinbin#172]
1. https://coinb.in/#verify
2. `010000000001a0860100000000001976a9145700e52bce4a0fceca7646a9614a46c2f364559f88ac00000000`
3. Submit
Result: `Unable to decode`
________________________________
1. https://ttutdxh-nubits.github.io/cointoolkit/#verify
2. Change mode - select BitCoin.
3. `010000000001a0860100000000001976a9145700e52bce4a0fceca7646a9614a46c2f364559f88ac00000000`
3. press "Verify" button.
Result: Success decoding raw transaction.
 
Source code: https://github.com/ttutdxh-nubits/cointoolkit
_______
Also in [coinbin-v1.2a from releases](https://github.com/OutCast3k/coinbin/releases) transaction verify working good, but in coinbin-v1.3 this is not working.

Fix this, please.
___________
P.S.: You can fix this, using next code:
1. coinbin.js:
```javascript
function decodeTransactionScript(){//...
//if (decode.witness.length>=1) {
if (typeof decode.witness !== 'undefined' /*exclude undefined for non-segwit transaction*/
&& decode.witness.length>=1) {
```
2.	coin.js:
```javascript
var obj = new coinjs.transaction();
obj.version = readAsInt(4);
//console.log(obj.version);
//if(buffer[pos] == 0x00 && buffer[pos+1] == 0x01){
if(obj.version!==1 /*or another identificator to exclude not segwit transaction*/
&& buffer[pos] == 0x00 && buffer[pos+1] == 0x01){
	// segwit transaction
```

**Comment by junderw** [comment]
Didn't work on either.

![_001](https://user-images.githubusercontent.com/11246316/50535435-4fe1c080-0b8d-11e9-88d5-8c5b5b9746cb.png)

**Comment by junderw** [comment]
Please read what I said:

The transaction you posted is an invalid format and can not be parsed by a proper application.

Any application that looks at that data and says "this is a valid transaction format" is wrong. The fact that is says "OK" when it SHOULD say "WRONG" means that the app is wrong.

Coinbin is correct here.

**Comment by junderw** [comment]
Here is the simplest English I can say:

This hex data:

"010000000001a0860100000000001976a9145700e52bce4a0fceca7646a9614a46c2f364559f88ac00000000"

is not a Bitcoin transaction.

Coinbin is right.

Brainwalletx and cointoolkit are wrong.

**Comment by username1565** [comment]
@junderw Ok, thanks.
If you have free time, you can fork and rewrite this client-side applications,
just for fun, and open the pull requests.
Bitcoin documentation is very hard to read and understanding.
