### ISSUE TITLE
Help figuring out TimeLock - Locked BTC

### ISSUE THREAD

**Issue by dpeim2016** [OutCast3k/coinbin#173]
I´m trying the time lock function, as it´s the only user friendly time lock that I know,

1) I created a timelocked address: 3BoRYBLQ9qCsrdvD7E4b7co4twDGABrr5i
I´m requiered to sign it with: 1H38KGDmN1QZdYSjAHirZsCGFEukuj7y9j
The redeem script is: 03ab7b08b1752103dbbefac75d4d0daea9894bdcf7ae704c8480719e57cae46fcc7ea6727a895f1fac

2) So I then generate this transaction (once the block 555947 has passed):
0100000001a1514025f92a3448e6b1ec53935793173f344ff9e9a90d451daa516411e8b589000000002903ab7b08b1752103dbbefac75d4d0daea9894bdcf7ae704c8480719e57cae46fcc7ea6727a895f1facffffffff01905f0100000000001976a9148150a7c747304266aef2e557ca861111a7d99c2288ac00000000

3) And then sign it with the private keys of: 1H38KGDmN1QZdYSjAHirZsCGFEukuj7y9j _This is the part I´m not sure, but these is the only private key that I have_

4) I get this signed transaction: 0100000001a1514025f92a3448e6b1ec53935793173f344ff9e9a90d451daa516411e8b5890000000073483045022100af4524540fae794a6bf240668211eb226fc75539d23b2445c7633a03175f58e602202f85a7a35a8a4dcd45730be5c2b5b0efe1f723b798102fdc9015e46a8c4803da012903ab7b08b1752103dbbefac75d4d0daea9894bdcf7ae704c8480719e57cae46fcc7ea6727a895f1facffffffff01905f0100000000001976a9148150a7c747304266aef2e557ca861111a7d99c2288ac00000000

5) When I try to broadcast it, I get an error: **64: non-mandatory-script-verify-flag (Locktime requirement not satisfied)**

What I´m missing or doing wrong?

Please advise, as I want to put more meaningful amounts, and also can I trust that this service will be still working for example 5 years from now? I want to put some BTC for my sons on TimeLock

Thank you

**Comment by OutCast3k** [comment]
Hi there,

It seems a bug existed when building at transaction which prevented you spending from a timelocked address. Your funds are totally safe, the bug is in the creation of the transaction not the address.

I've just fixed it and issued a few updates.

Please try again with the latest update, all my tests seem to show its working.

**Comment by dpeim2016** [comment]
Thanks! I have sent my transaction, everything is working fine now with this transaction and with another one created a couple of days before that had the same issue. 

Please help me understand more this service if possible: Can I trust this for 5 or 10 years to be online and working, does it even have to? Or can I save this and use it in the future? Maybe I can create and sign the future transaction now and just save it and broadcast it in the future after the timelock from anywhere that a transaction can be broadcasted?

**Comment by OutCast3k** [comment]
Its impossible to say but its very likely the addresses will still be valid in future, to many people use them now for the feature to be removed.

Further more, even if the coinb.in was offline and you couldn't obtain a copy as you have your private keys and redeem script you are good to go and can use it with bitcoin core or clients to recover your bitcoins.
