### ISSUE TITLE
Add Litecoin again ?

### ISSUE THREAD

**Issue by K2APacific** [OutCast3k/coinbin#175]
I really like your wallet. Thanks for building it ! I recall back in mid 2017 that Litecoin was still supported in the settings and then was removed due to a block explorer shutting down. Can you enable Litecoin support again please ? Also is it correct to say I can still use the 2017 version that had Litecoin support to generate offline Litecoin transactions ? (non Segwit addresses only of course). Thanks again.

**Comment by Wowee0** [comment]
I enabled Litecoin in https://github.com/Wowee0/coinbin/tree/litecoin, pull request https://github.com/OutCast3k/coinbin/pull/182.  Announced in Reddit (r/litecoin/comments/bf0sfp/coinbin_light_wallet_and_litecoin).  In reference to your 2nd question, the 2017 version uses a block explorer API that no longer exists.

**Comment by yottalogical** [comment]
Litecoin support is back as of today.

**Comment by OutCast3k** [comment]
Litecoins been re-added
