### ISSUE TITLE
Please support multisig addresses in Outputs

### ISSUE THREAD

**Issue by Stemby** [OutCast3k/coinbin#18]
Hi,
multisig addresses (3[...]) seem to be unsupported.

![coinbin](https://cloud.githubusercontent.com/assets/146789/8492039/65a38084-2144-11e5-9be8-d783beb347bc.png)

Thank you!

Carlo

**Comment by dabura667** [comment]
31uA87MHoaM7dsSsP8QiaHWtiDog9kQ7J6

In case anyone wants to copy paste.

**Comment by OutCast3k** [comment]
Sorry about this will have it fixed later today.

**Comment by dabura667** [comment]
https://github.com/OutCast3k/coinbin/blob/master/js/coinbin.js#L416

This should change from

```javascript
if(((a!="") && (ad.version == coinjs.pub || ad.version == coinjs.priv)) && $(".amount",o).val()!=""){ // address
```
to
```javascript
if(((a!="") && (ad.version == coinjs.pub || ad.version == coinjs.priv || ad.version == coinjs.multisig)) && $(".amount",o).val()!=""){ // address
```

I would fix it right now, but my git isn't setup on this computer and I don't have rights.

**Comment by dabura667** [comment]
Looks like this commit broke it:

https://github.com/OutCast3k/coinbin/commit/ef5cbdb61e2b4261ac53468406b3beed95a56ea7

I think you mistook version 5 for WIF privkey, WIF privkey is 128, not 5. (though base58 WIF starts with 5 lol)

**Comment by OutCast3k** [comment]
Yeah you're correct, I appear to have made a mistake. Fixed the issue now though. Thanks :)
