### ISSUE TITLE
Tor version does not retrieve transaction data

### ISSUE THREAD

**Issue by chmac** [OutCast3k/coinbin#181]
## Steps to reproduce

* Open tor browser
* Load the site
* Enter a bitcoin address with unspent outputs
* Click "Load"

## Expected behaviour

On the web version, the button changes to "Loading..." and then the "Inputs" tab is filled with unspent outputs from that address.

## Actual behaviour

On the tor version of the site, no network request is made, and a message appears immediately saying " Retrieved unspent inputs from address ***".

**Comment by OutCast3k** [comment]
i'm not able to reproduce the issue on my browser via TOR... but i'm not using the TOR browser.

I'm aware of other users experiencing similar issues with TOR too... At first I guessed it was cloudflare causing the problems by presenting the user with a captcha that they couldn't complete but I'm not totally sure.

**Comment by Geoffrey19** [comment]
I may have a version of the same problem. Unaware of chmac's post, I tried to transfer from a clearweb coinbin wallet to the coinbin onion wallet address. After several days, there's 0 balance showing. However when I click History, taking me to Blockcypher, it shows that I "received" the expected balance. (It also shows my admittedly tiny, 0.001 BTC donation to coinbin!) So something's up with the onion wallet. Hope I can recover my funds.

**Comment by Geoffrey19** [comment]
@OutCast3k 
What are you doing about this? I have money I can't reach.

**Comment by OutCast3k** [comment]
@geoffrey19

Annoyingly this bug doesnt seem to effect everyone, i suspect its cloudflare causing the issue but I'm not certain.

Can you please confirm, which browser and tor versions you are using, unfortunately I'm unable to reproduce this currently.

An alternative option to gain access to your funds is to disable tor and use clear net.

Let me know how you get on.

**Comment by OutCast3k** [comment]
I'm hoping to have fixed this issue in the latest update. 

please reopen if the issue continues.

**Comment by Geoffrey19** [comment]
Thanks for your reply!

I’m delighted and a little amazed that the funds finally showed up. I had been checking the onion site every ~3 days but less often lately as I am a newb and was working through Gpg and so forth. In any event, all’s well that ends well. I haven’t moved the money yet and probably won’t for a week or so.

FYI, was using Tails 3.14. I didn’t encounter any Captur that I was aware of. I didn’t follow your suggestion “to disable tor and use clear net.” I assumed you needed tor to visit a .onion site. Was there a way to reverse the transaction from the clear web?

Anyway, very appreciative.

Geoff
