### ISSUE TITLE
Coinbin does not recognize new Litecoin Multisig addresses

### ISSUE THREAD

**Issue by yottalogical** [OutCast3k/coinbin#184]
When testing out the new Litecoin support, I noticed that I wasn't unable to generate a transaction that sends to one of my new multisig addresses (beginning in 3). I then tried using the old version of that multisig address (beginning in M), and everything worked just fine.

The one that didn't work was `3K7F9uccgbYrmK8FpaB9Y9CD1rGxSXizYB`. I changed it to `MRKPTo2adiQHZpQ9vTAVMnScLYsQSFA8XF` in the Coinbin interface, and it worked just fine.

Keep in mind that these two are the exact same addresses, just using the new and old version of multisig addresses respectively.

**Comment by Wowee0** [comment]
3-addresses are deprecated, M-addresses are the currently supported ones.  The change was intentional.  The title of this issue, 'Coinbin does not recognize **new** Litecoin Multisig addresses' is incorrect.

**Comment by yottalogical** [comment]
I went back and double checked, and it turns out I read it wrong. The reference I was using was worded weirdly.
