### ISSUE TITLE
Add Transaction Fee Check And Alert If Higher Than Normal / Lower Than Suggested

### ISSUE THREAD

**Issue by imcoddy** [OutCast3k/coinbin#20]
Currently coinbin will just put total of all the inputs as the transaction fee and recalculate when user change output field dynamically.

This is pretty good but might cause some trouble, when user make some typo mistake and forget to change the fee, the large fee will just be gone :(

One suggestion is that when the fee is higher / lower than suggested, pop up a confirm dialog and let user check that before making a transaction.

**Comment by OutCast3k** [comment]
I've added a very basic check in the latest release. As of now, if the transaction fee is over 0.01 a warning will be displayed but the transaction can still be built!
