### ISSUE TITLE
Why cannot I transfer testnet bitcoins via coinb.in

### ISSUE THREAD

**Issue by salamsoliman** [OutCast3k/coinbin#200]
I went coinb.in settings page https://coinb.in/#settings, and changed the network into bitcoin testnet, and tried use the “Transaction” function, but I found I cannot type testnet pub key inside, does the bitcoin testnet  not work on this site?

**Comment by OutCast3k** [comment]
Hi,

Coinbin currently allows bitcoin main net for broadcasting and unspent input retrieval, but not bitcoin testnet.

You can still build testnet transactions and submit them manually via a testnet block explorer.

Full testnet support maybe added at a later date.

**Comment by smartm0use** [comment]
Any news on adding full support for testnet?
