### ISSUE TITLE
Muliple inputs are available ? (CoinJoin like..)

### ISSUE THREAD

**Issue by Itsik86** [OutCast3k/coinbin#21]
There is an option to enter couple of inputs ,to create coinjoin transaction?
Tnx

**Comment by OutCast3k** [comment]
Yes you can enter multiple inputs, click on the "inputs" tab on this page https://coinb.in/#newTransaction

Hope that helps.

**Comment by Itsik86** [comment]
Tnx my friend!
But its only loading 1 address every time,when i enter another address ,the
first one disappear for the new one ,if i press + so then nothing happens
when i enter the bar an utxo of some other address lets say ..
so how is it working?
Tnx!

**Comment by OutCast3k** [comment]
Hey,

It seems to be working for me. I can add multiple inputs (and outputs) 

Here is the steps I made:

1, Visit https://coinb.in/#newTransaction
2, Click the "inputs" tab
3, Enter your input and press the + (PLUS) button, this will create another row below. You can then press the plus button again or as many times as you want and create as many inputs as you want.

If this doesn't work can you please explain the steps you are taking, and also provide your O/S, browsers name and version. Maybe some screen shots?

Thanks

**Comment by Itsik86** [comment]
When i am in the "input" filed, i am only entering the "transaction ID "
data, i am not add nothing for the "N" and the "script" filed,maybe this is
the problem ? what are those fields ?
Because when i create a "regular" transaction with only 1 output,i just
copy the  output address to the "blue" bar,
*"Address, WIF key or Multisig Redeem Script"* and then all the "variables"
(transaction id, n , script) are full automatically.
Tnx!

**Comment by Itsik86** [comment]
this is for you guys by the way ,tnx for your development :
https://blockchain.info/tx/7bb173176ca39a998e45b3df5743aee41d36f2fe492f6117a29a50b7c1828f01

**Comment by Itsik86** [comment]
Help pleas? Tnx

**Comment by Itsik86** [comment]
Hi,you can help me pleas?
tnx

 " When i am in the "input" filed, i am only entering the "transaction ID "
data, i am not add nothing for the "N" and the "script" filed,maybe this is
the problem ? what are those fields ?
Because when i create a "regular" transaction with only 1 output,i just
copy the input address to the "blue" bar,
*"Address, WIF key or Multisig Redeem Script"* and then all the "variables"
(transaction id, n , script) are full automatically.
Tnx! "

**Comment by dabura667** [comment]
> add nothing for the "N" and the "script" filed

These fields are necessary for generating a valid transaction.

The automatic filling in of inputs only supports 1 address at a time.

If you would like to add multiple inputs from multiple addresses, you must enter each input manually and then copy the unsigned transaction into the sign page.

**Comment by Itsik86** [comment]
What is the "n" and the " script" fields?

**Comment by dabura667** [comment]
http://lmgtfy.com/?q=n+script+bitcoin+transaction

I'll give you a hint:
n = index
script = scriptPubkey of the referred transaction's output

**Comment by Itsik86** [comment]
Tnx my friend!

**Comment by Itsik86** [comment]
Hi,is it possible to enter multiple signatures at the "Sign transaction"
screen (because i have multiple inputs..) ?  and if its possible,what is
the way to do it? because when i tried ,i just push them one after another
and i got an error ...
Tnx again!
