### ISSUE TITLE
Question - BitPay's Insight-API?

### ISSUE THREAD

**Issue by neurocis** [OutCast3k/coinbin#22]
I am porting coinb.in to [PiggyCoin](https://www.piggy-coin.com) and it looks like the API coinb.in adheres to to retrieve transaction details and submit them to the network is [BitPay's Insight-API](https://github.com/bitpay/insight-api). I just want to confirm that is in fact the case.

**Comment by OutCast3k** [comment]
Hey,

Coinb.ins API isn't Bitpays insight api. No. But there is no reason why you couldn't make it work with insight. In fact, i'm actually working on this (hidden for now) page https://coinb.in/#settings which will allow the use of different APIs to be used. It will be ready soon.

**Comment by neurocis** [comment]
Found it! Thats great, mind a pull req. for PiggyCoin once I have our insight-api running?

**Comment by dabura667** [comment]
@neurocis Piggy-coin looks nice.

If you're going to port insight, I would recommend porting the following libraries as well:

https://github.com/bitpay/bitcore
https://github.com/bitpay/bitcore-payment-protocol
https://github.com/bitpay/bitcore-wallet-utils
https://github.com/bitpay/bitcore-wallet-client
https://github.com/bitpay/angular-bitcore-wallet-client
https://github.com/bitpay/bitcore-wallet-service
https://github.com/bitpay/copay

I think that a lot of the bitcore methods work by just calling the bitcore.networks object... so tbh "porting" would most likely just mean making the default networks object correspond with your coin in your bitcore fork.

Then you could run an official instance of bitcore-wallet-service alongside your sight and have a multi-platform wallet which supports multisig (I think you could modify Copay UI to be like a "parental permission" layer and take away the "multi-sig" jargon)

Then just build bws, point it to your piggy-coin insight instance, then code Copay to point to your BWS instance by default.

Cool thing is that we've got angular gettext in Copay, so localization is very easy. (Piggy coin in Spanish! yay!)

**Comment by neurocis** [comment]
@dabura667 Thanks, just finished the bitcore branch v1.0 port (was a bit more work as PIGGY is X11 and proof of stake) as well as the finished porting of coinb.in to grab UTXOs and Bcast via Insight. copay and BWS is actually the end-goal so you were reading my mind with the post.

Anyhow, all are available at [TeamPiggyCoin](https://github.com/TeamPiggyCoin).

Cheers!
