### ISSUE TITLE
How to run it from command line

### ISSUE THREAD

**Issue by ghost** [OutCast3k/coinbin#241]
Hello,

How can I pass a key for this to verify from the command line from shell script instead of using the web browser?

nodejs ... something

**Comment by junderw** [comment]
What exactly are you trying to verify?

There are a bunch of tools that cover certain features of coinbin, but we'd need to know what specific things you want to verify.

**Comment by ghost** [comment]
I want to script it like this:

./verify.sh privatekey

If it's a valid private key it returns with the public key if not then some ERROR message

**Comment by junderw** [comment]
1. Install bitcoinjs-lib
2. Save below to `verify.js`
3. Run `node verify.js KyW1VtQNYogmdJ1bRtpNW9mvTRexLi5e3xXnDoLBuG477LRyXML5`

```js
// First install bitcoinjs-lib
// npm install bitcoinjs-lib@^5.2.0
const bitcoinjs = require('bitcoinjs-lib')
const mainnet = bitcoinjs.networks.bitcoin
const testnet = bitcoinjs.networks.testnet

function getInfo(wifPrivateKey, network) {
  network = network || mainnet

  const keyPair = bitcoinjs.ECPair.fromWIF(wifPrivateKey, network)
  return {
    address: bitcoinjs.payments.p2pkh({ pubkey: keyPair.publicKey, network }).address,
    publicKey: keyPair.publicKey.toString('hex'),
    privateKey: keyPair.privateKey.toString('hex'),
    compressed: keyPair.compressed,
  }
}

function main(wif, networkName) {
  networkName = networkName || 'mainnet'
  const network = ({
    mainnet: mainnet,
    testnet: testnet,
  })[networkName]

  console.log(getInfo(wif, network))
}

main(process.argv[2], process.argv[3])
```
