### ISSUE TITLE
Verifier shows wrong number of signatures for P2SH multisig

### ISSUE THREAD

**Issue by dexX7** [OutCast3k/coinbin#33]
Hey there,

when verifying a 4-of-5 P2SH multisig transaction, which has only 3 signatures, then the UI neverthess indicates there are 4 signatures (instead of 3):

![coinbin](https://cloud.githubusercontent.com/assets/5836089/11258404/0a1fc006-8e59-11e5-874a-1b31253a73ac.png)

[Link to transaction](https://coinb.in/?verify=0100000001f72efade5690ab939aa121c436101ff0debc7e5f05638b6366aa2fe144a707a200000000fdeb010047304402204efd71dbfae55e47fa0a6afc3d58fc98fa8396a59ae0adf81db33b753317ee4b02201de76d8d9b055ea7f1efea50fc57feb904a11f603d91492b7330cba25c0c8c480147304402206016fcbea57a75a2c6fd3853a52acdf25b5ba6944c6df54119dd5b258d3133cf022029189e5062332640e4114451f40f6845e24c7a412445c84dd6ab90263a1a85c001483045022100fccfe83fc59dcd669709f1598dcdb5e8f2007a9b1255c7aab0a9caf4f4d0105202204ebb2c3e4e821a320010adc11f8d15f087ce08f419a8201af6f949fa335e559d01004d0d01542102d797b8526701a3dfdb52d11f89377e0288b14e29b1414d64de065cd337069c3b21036a4caa95ec1d55f1b75a8b6c7345f22b4efc9e25d38ab058ef7d6f60b3b744f7410499e86235a6a98fc295d7cfe641d37409f2840ad32e0211579cae488bd86cf01daf7ad8f082d968ea4bca77e794fffd1a31583f36f37b1198e51d0651cdbcf3214104b7a3d7f7ccdf211dfd180815b87332b4773cc40bff72a4d0bb60f3a85409d19f99709331c6b11c976fe274a86d789a1cf2b3b0be29fe5fc55c93ad9e08459c4f4104e65b098558d637cfcf3194214637f8838338b141259b698d2a027b069d405b6502ad4a4e9aa75094fa431a6c9af580f5917834a6d4cec946054df33194b2967855aeffffffff03ac020000000000004751210394abb6fe6d492495f855ab3fa29acd6be04f347d17597985da0e8c70a26036f2210258785fd620c3f80f730dc719245d71109e546d1f00f0acf95b338c6109855a1252ae22020000000000001976a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac22020000000000001976a914f7958092f4af2ca5f90ef592f9eb9732d06c814188ac00000000#verify)

**Comment by OutCast3k** [comment]
Hi,

Thanks for the bug report.

Do you have a copy of that transaction you could paste? if not no big deal.

**Comment by dexX7** [comment]
Hi @OutCast3k, thanks for getting back to me!

Sure, [here is the link](https://coinb.in/?verify=0100000001f72efade5690ab939aa121c436101ff0debc7e5f05638b6366aa2fe144a707a200000000fdeb010047304402204efd71dbfae55e47fa0a6afc3d58fc98fa8396a59ae0adf81db33b753317ee4b02201de76d8d9b055ea7f1efea50fc57feb904a11f603d91492b7330cba25c0c8c480147304402206016fcbea57a75a2c6fd3853a52acdf25b5ba6944c6df54119dd5b258d3133cf022029189e5062332640e4114451f40f6845e24c7a412445c84dd6ab90263a1a85c001483045022100fccfe83fc59dcd669709f1598dcdb5e8f2007a9b1255c7aab0a9caf4f4d0105202204ebb2c3e4e821a320010adc11f8d15f087ce08f419a8201af6f949fa335e559d01004d0d01542102d797b8526701a3dfdb52d11f89377e0288b14e29b1414d64de065cd337069c3b21036a4caa95ec1d55f1b75a8b6c7345f22b4efc9e25d38ab058ef7d6f60b3b744f7410499e86235a6a98fc295d7cfe641d37409f2840ad32e0211579cae488bd86cf01daf7ad8f082d968ea4bca77e794fffd1a31583f36f37b1198e51d0651cdbcf3214104b7a3d7f7ccdf211dfd180815b87332b4773cc40bff72a4d0bb60f3a85409d19f99709331c6b11c976fe274a86d789a1cf2b3b0be29fe5fc55c93ad9e08459c4f4104e65b098558d637cfcf3194214637f8838338b141259b698d2a027b069d405b6502ad4a4e9aa75094fa431a6c9af580f5917834a6d4cec946054df33194b2967855aeffffffff03ac020000000000004751210394abb6fe6d492495f855ab3fa29acd6be04f347d17597985da0e8c70a26036f2210258785fd620c3f80f730dc719245d71109e546d1f00f0acf95b338c6109855a1252ae22020000000000001976a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac22020000000000001976a914f7958092f4af2ca5f90ef592f9eb9732d06c814188ac00000000#verify) to the transaction on coinb.in, and here is the raw transaction:
```
0100000001f72efade5690ab939aa121c436101ff0debc7e5f05638b6366aa2fe144a707a200000000fdeb010047304402204efd71dbfae55e47fa0a6afc3d58fc98fa8396a59ae0adf81db33b753317ee4b02201de76d8d9b055ea7f1efea50fc57feb904a11f603d91492b7330cba25c0c8c480147304402206016fcbea57a75a2c6fd3853a52acdf25b5ba6944c6df54119dd5b258d3133cf022029189e5062332640e4114451f40f6845e24c7a412445c84dd6ab90263a1a85c001483045022100fccfe83fc59dcd669709f1598dcdb5e8f2007a9b1255c7aab0a9caf4f4d0105202204ebb2c3e4e821a320010adc11f8d15f087ce08f419a8201af6f949fa335e559d01004d0d01542102d797b8526701a3dfdb52d11f89377e0288b14e29b1414d64de065cd337069c3b21036a4caa95ec1d55f1b75a8b6c7345f22b4efc9e25d38ab058ef7d6f60b3b744f7410499e86235a6a98fc295d7cfe641d37409f2840ad32e0211579cae488bd86cf01daf7ad8f082d968ea4bca77e794fffd1a31583f36f37b1198e51d0651cdbcf3214104b7a3d7f7ccdf211dfd180815b87332b4773cc40bff72a4d0bb60f3a85409d19f99709331c6b11c976fe274a86d789a1cf2b3b0be29fe5fc55c93ad9e08459c4f4104e65b098558d637cfcf3194214637f8838338b141259b698d2a027b069d405b6502ad4a4e9aa75094fa431a6c9af580f5917834a6d4cec946054df33194b2967855aeffffffff03ac020000000000004751210394abb6fe6d492495f855ab3fa29acd6be04f347d17597985da0e8c70a26036f2210258785fd620c3f80f730dc719245d71109e546d1f00f0acf95b338c6109855a1252ae22020000000000001976a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac22020000000000001976a914f7958092f4af2ca5f90ef592f9eb9732d06c814188ac00000000
```

**Comment by OutCast3k** [comment]
I believe the issue was caused during the signing process. A patch has recently been issued. I believe If you resign the transaction (or discard it and start again) it should resolve it.

**Comment by dexX7** [comment]
Hey @OutCast3k,

this transaction was not signed via coinb.in, but just checked:

[Link to transaction](https://coinb.in/?verify=0100000001f72efade5690ab939aa121c436101ff0debc7e5f05638b6366aa2fe144a707a200000000fdeb010047304402204efd71dbfae55e47fa0a6afc3d58fc98fa8396a59ae0adf81db33b753317ee4b02201de76d8d9b055ea7f1efea50fc57feb904a11f603d91492b7330cba25c0c8c480147304402206016fcbea57a75a2c6fd3853a52acdf25b5ba6944c6df54119dd5b258d3133cf022029189e5062332640e4114451f40f6845e24c7a412445c84dd6ab90263a1a85c001483045022100fccfe83fc59dcd669709f1598dcdb5e8f2007a9b1255c7aab0a9caf4f4d0105202204ebb2c3e4e821a320010adc11f8d15f087ce08f419a8201af6f949fa335e559d01004d0d01542102d797b8526701a3dfdb52d11f89377e0288b14e29b1414d64de065cd337069c3b21036a4caa95ec1d55f1b75a8b6c7345f22b4efc9e25d38ab058ef7d6f60b3b744f7410499e86235a6a98fc295d7cfe641d37409f2840ad32e0211579cae488bd86cf01daf7ad8f082d968ea4bca77e794fffd1a31583f36f37b1198e51d0651cdbcf3214104b7a3d7f7ccdf211dfd180815b87332b4773cc40bff72a4d0bb60f3a85409d19f99709331c6b11c976fe274a86d789a1cf2b3b0be29fe5fc55c93ad9e08459c4f4104e65b098558d637cfcf3194214637f8838338b141259b698d2a027b069d405b6502ad4a4e9aa75094fa431a6c9af580f5917834a6d4cec946054df33194b2967855aeffffffff03ac020000000000004751210394abb6fe6d492495f855ab3fa29acd6be04f347d17597985da0e8c70a26036f2210258785fd620c3f80f730dc719245d71109e546d1f00f0acf95b338c6109855a1252ae22020000000000001976a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac22020000000000001976a914f7958092f4af2ca5f90ef592f9eb9732d06c814188ac00000000#verify)

It still shows 4 signatures, while only 3 are provided.
