### ISSUE TITLE
Trim Public Keys when creating a multi-sig

### ISSUE THREAD

**Issue by myveryown** [OutCast3k/coinbin#39]
I created a multi-sig adress i am unable to sign off on - as one of the keys i used had an extra space char on the end of it - which went un noticed until it was time to sign a transaction when i then found it could not be signed.

My mistake for not checking the key I know - but it would have been nice if coinb.in had warned me that a key was invalid or simply trimmed the white space at the end

Thanks

**Comment by myveryown** [comment]
These keys should yeild the address 347ynSLeoNXE9EG47Dwv7jajoDJ5qpyR5o

048025D2A4D154426288BFEDC6204CD3CED532298F50A3F46F72C62B0370536D1B537022EE2B25B597C0CB75667979D58672C564F83527AC782EB659BED2C44F63

0473c074064a58503b1050b09e8fe407d15358111e178c60adbdf52da161433dae41e00f2241a97834d2127ed9490a70e619f7e136dc00128a4c879cb4eb0c749b 

04C233878844210A04AA0F23332DF429B8A28EA527E488ED1FC96942D04EBA89954638D2EA73485EE9BA867AC783231F381A6A63E09E651ACF7329C79524CB914D

however if you use "0473c074064a58503b1050b09e8fe407d15358111e178c60adbdf52da161433dae41e00f2241a97834d2127ed9490a70e619f7e136dc00128a4c879cb4eb0c749b " as the middle key you get 35qChFUjBbBoJgiWgcRxo1BoFNwpHa8Y72
 and are unable to sign off on an output tx

**Comment by myveryown** [comment]
3 of 3 multisig

**Comment by OutCast3k** [comment]
This has been fixed in the latest update. Thanks and sorry about this.
