### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by NxtChg** [OutCast3k/coinbin#45]
If a script object is passed to coinjs.script() it causes this line to be executed:

else if (data instanceof coinjs.script) {
	r.buffer = r.buffer;
} 

Shouldn't it be "r.buffer = data.buffer;"? Or what's the intent here?

**Comment by NxtChg** [comment]
Another bug:

coinjs.numToBytes = function(num,bytes) {
	if (typeof bytes === undefined) bytes = 8;

'undefined' must be a string, otherwise it doesn't work.

Luckily you never omit the 'bytes' argument anywhere.

**Comment by NxtChg** [comment]
Another bug:

	coinjs.numToVarInt = function(num) {
		if (num < 253) {
			return [num];
		} else if (num < 65536) {
			return [253].concat(coinjs.numToBytes(num,2));
		} else if (num < 4294967296) {
			return [254].concat(coinjs.numToBytes(num,4));
		} else {
			return [253].concat(coinjs.numToBytes(num,8));
		}
	}

Last line must be:
return [255].concat(coinjs.numToBytes(num,8));

**Comment by NxtChg** [comment]
Major bug in clone():

        var temp = obj.constructor();

must be

        var temp = new obj.constructor();

Not only it's wrong to just call obj.constructor(), but this also fails cloning completely if transaction has any outputs, because the BigInteger 'value' copying crashes: a simple call returns 'undefined' in that case.

**Comment by NxtChg** [comment]
In deterministicK() these lines make no sense:

	var v = new Uint8Array(32);
	v = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

	var k = new Uint8Array(32);
	k = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

There is no need to use Uint8Array(32) if you immediately overwrite it with a regular array.

**Comment by OutCast3k** [comment]
Hey, thanks for all your support in reviewing the code, if you aren't able to submit a pull request I'll make the amendments shorty.

**Comment by NxtChg** [comment]
It would be easier for you to just make all the changes. I rewrote a lot of coin.js and removed 2/3 of the code, so my version differs too much.

**Comment by OutCast3k** [comment]
your suggestions have been made and are now live. thanks.
