### ISSUE TITLE
Does the HD wallet generator work correctly?

### ISSUE THREAD

**Issue by thinkloop** [OutCast3k/coinbin#47]
Hello, it's very possible I am doing something wrong, but it seems the xpub's for the HD wallets aren't matching up with generated addresses. I did the following:

1. Click "New" from the top menu
2. Choose HD Address
3. Click "generate"
4. Click the arrow next to "xPub Address" to see derived addresses
5. Under the "Keys" heading select one off the "address"
6. Send tx to that address
7. Verify tx exists on blockchain.info (it does)

Now if I try to monitor the xpub for any transactions using Sentinel (app), or Bitcoin Balance (app) or Blockchain.info the transaction isn't shown.

Here is an example xpub and transaction:

[XPUB ](https://blockchain.info/xpub/xpub661MyMwAqRbcEbtdUQeDpPvpTE9sNVXb5FEnJU1GTP3Rya9y1kSvh7GJwuub49ZfZYfgMKtbErkfGe58pjGHdHPoqqZydqJjqgcbju5Nq8D)
```
xpub661MyMwAqRbcEbtdUQeDpPvpTE9sNVXb5FEnJU1GTP3Rya9y1kSvh7GJwuub49ZfZYfgMKtbErkfGe58pjGHdHPoqqZydqJjqgcbju5Nq8D
```

[TRANSACTION](https://blockchain.info/address/1T5N1jnUnALY25TBqXCNgAsszWHJQucpj)
```
1T5N1jnUnALY25TBqXCNgAsszWHJQucpj
```

**Comment by dabura667** [comment]
All those apps you show watch a specific path of the xpub.

`X/0/k` and `X/1/k` where X represents the xpub you input, and k is the index of the key starting with 0 and counting up.

Coinbin merely shows you `m/i` where i is the index of the key (k in my example)

Because the paths are different, you get different keys.

**Comment by thinkloop** [comment]
Thanks for the response. 

Should I be able to add a "/0" to the end of the xpub to check out the tx, something like: https://blockchain.info/xpub/xpub661MyMwAqRbcEbtdUQeDpPvpTE9sNVXb5FEnJU1GTP3Rya9y1kSvh7GJwuub49ZfZYfgMKtbErkfGe58pjGHdHPoqqZydqJjqgcbju5Nq8D/0

Do you know of any services that allow you to check all tx's based on xpub?

**Comment by thinkloop** [comment]
![image](https://cloud.githubusercontent.com/assets/118814/13466120/9269e338-e066-11e5-8ada-327566385db1.png)

**Comment by dabura667** [comment]
https://bip32jp.github.io/english/

You can move your mouse around for a couple seconds (it will gather randomness from that to add to key generation) and then click "Generate New Phrase" and it will generate a new BIP39 phrase for you.

Then you can change the path methodology. (BIP44 is most popular)

If you paste your own xpub or xprv into the "BIP32 Extended Key" box, it will ignore all data above that, and let you derive from the xpub/xprv that you input.

Using the "Custom" derivation path will allow you to write whatever path you wish. Just know that `m` in the path is always referring to the xpub/xprv in the box, regardless of where that xpub/xprv came from (it could be the 45th derivation layer, but my app refers to it as `m` when you input the path.

**Comment by thinkloop** [comment]
Thanks for the info! I'm surprised there isn't a simple app that lets you plugin an xpub and have it monitor any related transactions - I kind'of thought that was one of the main features of having a hierarchical master public key. Do you think I should build one?

**Comment by dabura667** [comment]
> I kind'of thought that was one of the main features of having a hierarchical master public key.

Copay and Mycelium let you do it.

Mycelium lets you plug in an xpub, but Copay requires that the wallet be made on Copay and then you have the option to delete the private keys and only leave the xpub on the wallet (this assumes you wrote down your seed phrase)

> Do you think I should build one?

The more the merrier, I say.

**Comment by thinkloop** [comment]
:+1:
