### ISSUE TITLE
Making a transaction: N, Script, Change Addresses?

### ISSUE THREAD

**Issue by thinkloop** [OutCast3k/coinbin#48]
Hello,

How does change get handled when making a transaction using the New Transaction interface?

Also, any suggestion for what values to put for N and Script:

![image](https://cloud.githubusercontent.com/assets/118814/13526898/1673a146-e1d9-11e5-8a9a-eec4fbc3c05f.png)

Thanks!

**Comment by OpenProvenance** [comment]
you need to load an address, private key or multisig redeem script for those fields to be populated - and you specifiy your own change address in the outputs tab

**Comment by thinkloop** [comment]
Thank you.

Any idea why this is marked invalid:

![image](https://cloud.githubusercontent.com/assets/118814/13531749/20123c7c-e1f6-11e5-9b01-1411e2a4af5f.png)

Also when specifying the amount for a change address, do I have to calculate the resulting amount minus the fee? For example: `unpent - main amount - fee = change amount'?

**Comment by OpenProvenance** [comment]
the fee will auto calculate itself as inputs-outputs = fee, no idea why invalid

**Comment by thinkloop** [comment]
Thanks again. Any idea what the possibilities are for why something could be invalid?

**Comment by thinkloop** [comment]
Refreshing and started over did the trick
