### ISSUE TITLE
CheckLockTimeVerify totally doesn't work

### ISSUE THREAD

**Issue by hopeseekr** [OutCast3k/coinbin#55]
It consistently says that "The Public key and/or date is invalid" while highlighting the public key box.

Public key: 1H8Cer35EMwkQabXAGpb23uBQNJVGWAoXs
Date: 07/17/2016 15:50

**Comment by dabura667** [comment]
That's not your public key.

That's your address.

**Comment by hopeseekr** [comment]
You're right. I learned something new! I guess using Mycelium is straight out? :-/

**Comment by dabura667** [comment]
This site is not for use with Mycelium or any other wallet.

This site is for managing raw keys.

If you don't know the difference between an address and a public key, using this site is dangerous and you can lose your money, so I highly recommend sticking with an easy to use wallet like Mycelium until you become more comfortable with bitcoin concepts.
