### ISSUE TITLE
Invalid Character

### ISSUE THREAD

**Issue by greenbigfrog** [OutCast3k/coinbin#58]
After submitting totally fine/normal stuff the codes throwing some invalid character error:
![image](https://cloud.githubusercontent.com/assets/6208894/17817464/f0c9b904-663e-11e6-98a4-6b01472786cf.png)

**Comment by greenbigfrog** [comment]
nvm. Accidentally got public and private key mixed up.

**Comment by tomcarbon** [comment]
Good as time as any to introduce myself.. hi OutKast3k!

I've leveraged the coinb.in code to create dogecoinmultisig.org (check out the About page). I basically released it to the dogecoin community with this thread (https://redd.it/4ygk7x). 

It's still got some work to do (I'm calling it Alpha for now), but it's pretty tight overall. I had to change a hard-coded '5'  in coinbin.js to 'coinjs.multisig' (line 706) to get the output to correctly pay out to a multisig, and a few other tweaks. peoplma suggested I give a pull request, I'm new to this, but plan to do so. Also the site will have its own github, shortly.

As I introduce myself (u/tomcarbon), I would like to say THANK YOU for the solid coinb.in code from which this site is mainly based.

**Comment by tomcarbon** [comment]
oh, and good chance this is also flowing out to become bitcoinmultisig.org (and maybe litecoin as well). 

WR
Tom

**Comment by dabura667** [comment]
Console logging is great, but be careful what you log. (Don't log sensitive info by default, require a development flag)

And be concise with log text, it makes things easier to debug, and your witty log text is only funny maybe once, depending on the dev.

**Comment by greenbigfrog** [comment]
@tomcarbon Didn't even notice that this isn't dogemultisig related... just clicked the github link... maybe you should make that more clear...

**Comment by tomcarbon** [comment]
@dabura667 ...Console logging -  Thanks for the advice - I can really use it. I'll make sure this is cleaned up prior to this program being uploaded to github.

@greenbigfrog, I fixed that, thank you! I'm now pointing to the correct github (for dogecoinmultisig.org. It's a placeholder for now but at least I'm not stepping on @OutCast3k's github account. OutCast3k, I apologize for that!)
