### ISSUE TITLE
can not broadcast by using mobile or computer 

### ISSUE THREAD

**Issue by stone2y** [OutCast3k/coinbin#61]
Hi, 
Usually, when I used my mobile phone to broadcast the BTC transaction via coinb.in , 
But suddenly, I can not broadcast BTC transactions anymore. 
When I click submit, not TXID generated. 

Please help me to solve my problems. 

thank you.

**Comment by OutCast3k** [comment]
Hi,

Sorry about this. I've since fixed the problem.

All the best
