### ISSUE TITLE
sibcoin

### ISSUE THREAD

**Issue by titonik** [OutCast3k/coinbin#74]
i lost or am dumb and cant find my sibcoin i bought, i  used a web wallet, i have transaction details, and will pay anyone who can help me find my coins, they were either phished or im a dumb newb thx

**Comment by dabura667** [comment]
This site has nothing to do with siacoin.

**Comment by titonik** [comment]
its sibcoin not siacoin, but there is a code to recover it,i  may have been scammed, adress etc, is there anything i can do?

**Comment by dabura667** [comment]
This site has nothing to do with sibcoin.

**Comment by titonik** [comment]
how about helping me out with miners then, i can't connect to a remote node
using my mac, i open up the cli icon and the nonzero d, i sent some test
point ones the chain was running, wallet said it should of been working,
and i ended up donating miners to to the universe, i can't figure out how
to get the monero working 4 the life of me, also my money is stuck right
now on mymonero, yet i feel its the safest there becuz my computer is 10
years old, can't download the blockchain right, and i end up donating money
cuz i cant figure out a remote node, i am very untech savvy, if u know
anyone in el paso u trust, ill pay them big money to help me.... i just
want a working wallet that isn't a web wallet

**Comment by titonik** [comment]
monero not miners sorry

**Comment by OutCast3k** [comment]
Sorry coinb.in is not the same thing. Hope you resolved your issues.
