### ISSUE TITLE
Can't sign a transaction

### ISSUE THREAD

**Issue by patriczek** [OutCast3k/coinbin#84]
When i want sign my transaction with private key, then i get exactly same string as transaction.
And if i try to verify this string it isn't verify

**Comment by fizgig10** [comment]
I have the same issue.

**Comment by OutCast3k** [comment]
Please provide exact steps ideally with screen shots or some very specific data to carefully reproduce this bug in a new ticket. Thanks

**Comment by youssefgh** [comment]
Please re-open ! i created a RBF TX for this one : 5a44f6f676b13d4c65038d116ead455ebc354e24cc6ebe5228e71a01fd5cd558 and as a result i have this none signed TX : 0100000002acbcdb4274694094b868ddd18efe6afa9694d8501a19056db85df77b3766caa5000000001976a9146634d81558a22d9a1ac0348439a6f805cf41a06b88acfdffffff58d55cfd011ae72852be6ecc244e35bc5e45ad6e118d03654c3db176f6f6445a000000001976a9146634d81558a22d9a1ac0348439a6f805cf41a06b88acfdffffff01a2632400000000001976a9146634d81558a22d9a1ac0348439a6f805cf41a06b88ac00000000
i tried to sign it with my BIP32 private key, i decoded it and tried with the decoded one. But i always get the unsigned TX as a result
