### ISSUE TITLE
Altcoin support?

### ISSUE THREAD

**Issue by zilveer** [OutCast3k/coinbin#89]
Hello,
is there any guide on how to add altcoin support for coinbin?

Also I would like to know if there is any special altcoins supported by coinbin for example blackcoin, bitbay or any other coin?

**Comment by raedah** [comment]
I would like Decred support, and am willing to work with any devs to make this happen.

**Comment by zilveer** [comment]
Hello,
Decred is that a coin ?

**Comment by raedah** [comment]
Yes, decred.org DCR

**Comment by zilveer** [comment]
@raedah what is your email address?
I might get it fixed..

**Comment by raedah** [comment]
@zilveer thazoh@gmx.com

**Comment by OutCast3k** [comment]
I'll write a little guide shortly, but in general add the code and submit a pull request.
