### ISSUE TITLE
RBF rebroadcast with higher fee

### ISSUE THREAD

**Issue by sashamd** [OutCast3k/coinbin#92]
https://blockchain.info/pushtx gives:
Transaction is trying to double spend. Input 0 is already spent.

**Comment by dabura667** [comment]
Blockchain.info does not support pushing RBF yet.

**Comment by sashamd** [comment]
You're right, with blockr.io it works perfectly, thanks.

**Comment by sashamd** [comment]
0.002729778 is due.

**Comment by vetal20600** [comment]
@sashamd can you describe your steps?

**Comment by sashamd** [comment]
Select the network you wish to broadcast the transaction via Blockr.io (Bitcoin mainnet) then broadcast. The problem is today Blockr.io has replied with transaction ID but that ID isn't found in the mempool.
