### ISSUE TITLE
Bitcoin Confirmations

### ISSUE THREAD

**Issue by coughingvan** [OutCast3k/coinbin#96]
My wallet history only shows that I received two deposits of bitcoin but it doesn't show that I sent them out as well. The receiving end says it's waiting for confirmations. I can't speed it up because I don't have the transaction IDs. 

What are my options here? Will I have to wait weeks for my coins to get confirmed?

**Comment by OutCast3k** [comment]
Yes you'd likely have to wait unless you import your raw keys and build a custom transaction.
