### ISSUE TITLE
coinbin transaction problem

### ISSUE THREAD

**Issue by cooper320** [OutCast3k/coinbin#97]
my coinb.in address is
1CF7TjzTLAkK5xJDAmHzD5APgQokzRjFMs i sent .03761935 with a .0004 transaction fee to 14JqcgchhsQQv7LovnvA2ZCBgs14H88znN im not really sure of the tx id i didnt save it and dont no how to get it. the transaction doesnt show up on the blockchain link from your site but does show up on a different one. it says unconfirmed and its been 24 hours. why do all my coinbin transactions take for ever and coinbase goes right through. also the adress i sent this transaction to changed hours after i sent it. will it go through can i get this back? it was to another wallet pls help

**Comment by OutCast3k** [comment]
Looking at the blockhcain history of your address https://blockchain.info/address/1CF7TjzTLAkK5xJDAmHzD5APgQokzRjFMs it looks like your transactions have been confirmed. 

Sometimes transactions can take longer depending on your fee, nothing else. Next time set a higher fee.

All the best.
